# strategies/text.py
import os
import stat
from pathlib import Path
from .base import FileStrategy

class TextStrategy(FileStrategy):
    def process(self, source_file: Path, repo_root: Path):
        # 1. Calculate the path for the {{ include }} directive
        # This must be relative to the wrapper repo root (e.g. vendor/ml4w/dotfiles/...)
        include_path = source_file.relative_to(repo_root)
        
        # 2. Calculate the destination path (Chezmoi layout)
        # We need to map the source structure to the chezmoi structure relative to the repo root
        # e.g. source: .../dotfiles/.config/hypr/hyprland.conf
        #      rel:    .config/hypr/hyprland.conf
        #      dest:   dot_config/hypr/hyprland.conf.tmpl
        
        # Determine relative path from the "Virtual Home" (the dotfiles folder)
        # We assume source_file is inside vendor/ml4w/dotfiles
        # We can find 'dotfiles' in the path components to anchor us.
        parts = source_file.parts
        try:
            # Find where 'dotfiles' is in the path to anchor our relative path
            idx = parts.index('dotfiles')
            rel_parts = parts[idx+1:] # Everything after 'dotfiles'
        except ValueError:
            # Fallback if 'dotfiles' isn't in path (unlikely given setup)
            rel_parts = source_file.relative_to(repo_root / "vendor/ml4w").parts

        # Map to Chezmoi conventions (replace leading dots with dot_)
        dest_parts = []
        for part in rel_parts:
            if part.startswith('.'):
                dest_parts.append('dot_' + part[1:])
            else:
                dest_parts.append(part)
        
        # Construct destination
        dest_path = repo_root.joinpath(*dest_parts)
        
        # Handle Executable prefix
        is_exec = bool(os.stat(source_file).st_mode & stat.S_IXUSR)
        if is_exec:
            dest_path = dest_path.with_name(f"executable_{dest_path.name}")
            
        # Add .tmpl suffix
        dest_path = dest_path.with_name(f"{dest_path.name}.tmpl")

        # Ensure directory exists
        dest_path.parent.mkdir(parents=True, exist_ok=True)

        with open(dest_path, 'w') as f:
            f.write(f'{{{{/* Generated by Wrapper Script */}}}}\n')
            f.write(f'{{{{ include "{include_path}" }}}}\n')
            f.write(f'{{{{/* Append Custom Overrides Below */}}}}\n')
            
        print(f"   [Text]    {dest_path.relative_to(repo_root)}")