import os
import stat
from pathlib import Path
from .base import FileStrategy

class TextStrategy(FileStrategy):
    def process(self, source_file: Path, target_dir: Path, source_root: Path):
        # Check executable permission
        is_exec = bool(os.stat(source_file).st_mode & stat.S_IXUSR)
        prefix = "executable_" if is_exec else ""
        
        # Calculate relative path for the include
        # This path is relative to the directory where 'chezmoi apply' is run (usually source root)
        rel_path = source_file.relative_to(source_root.parent) 

        dest_filename = f"{prefix}{source_file.name}.tmpl"
        dest_path = target_dir / dest_filename

        with open(dest_path, 'w') as f:
            f.write(f'{{{{/* Generated by Wrapper Script */}}}}\n')
            # We assume the vendor directory is inside the source root
            f.write(f'{{{{ include "{rel_path}" }}}}\n')
            f.write(f'{{{{/* Append Custom Overrides Below */}}}}\n')
            
        print(f"   [Text]    Generated {dest_filename}")